name: ci
on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: test-unit
        run: make test-unit
