baseURL: https://fuse.heytobi.dev/
title: Fuse Documentation
languageCode: "en-us"

module:
  imports:
    - path: github.com/alex-shpak/hugo-book

disablePathToLower: true
enableGitInfo: true

# Needed for mermaid/katex shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1

menu:
  # before: []
  after:
    - name: "Github"
      url: "https://github.com/beverlyRoadGoose/fuse"
      weight: 10
    - name: "Website"
      url: "https://heytobi.dev"
      weight: 20

params:
  BookRepo: https://github.com/beverlyRoadGoose/fuse
  BookEditPath: edit/main/docs
  #BookLogo: /images/fuse.png enable when there's a bigger image, just looks sad now
